export default [
    {
        "networkid":"MON003",
        "urlforenrollmentpayment":"https://ssoprod.healthplan.com/sp/ACS.saml2",
        "avcalculatoroutputnumber":0.618337571620941,
        "designtype":"Not Applicable",
        "tehbdedinntier1familypergroup":"$12800 per group",
        "tehbinntier1familypergroupmoop":"$14300 per group",
        "standardcomponentid":"74483MO0040012",
        "sbchavingababycoinsurance":"$0",
        "serviceareaid":"MOS003",
        "firsttierutilization":"100%",
        "tehboutofnetfamilyperpersonmoop":"per person not applicable",
        "tehboutofnetindividualmoop":"Not Applicable",
        "tehbdedoutofnetfamilyperperson":"per person not applicable",
        "csrvariationtype":"Limited Cost Sharing Plan Variation",
        "tehbdedcombinnoonindividual":"Not Applicable",
        "ishsaeligible":"No",
        "tehbinntier1familyperpersonmoop":"$7150 per person",
        "sbchavingdiabetescoinsurance":"$770",
        "wellnessprogramoffered":"No",
        "businessyear":"2017",
        "tehboutofnetfamilypergroupmoop":"per group not applicable",
        "dentalonlyplan":"No",
        "sbchavingdiabetesdeductible":"$140",
        "diseasemanagementprogramsoffered":"Asthma, Heart Disease, Diabetes, High Blood Pressure & High Cholesterol, Pregnancy",
        "hiosproductid":"74483MO004",
        "importdate":"2017-01-20T09:19:19+00:00",
        "marketcoverage":"Individual",
        "tehbcombinnoonfamilypergroupmoop":"per group not applicable",
        "tehbdedcombinnoonfamilypergroup":"per group not applicable",
        "tin":"59-1031071",
        "outofcountrycoveragedescription":"Emergency Services Only",
        "sbchavingdiabetescopayment":"$750",
        "outofcountrycoverage":"Yes",
        "sbchavingsimplefracturelimit":"$0",
        "qhpnonqhptypeid":"Both",
        "tehbdedoutofnetfamilypergroup":"per group not applicable",
        "sbchavingsimplefracturedeductible":"$0",
        "urlforsummaryofbenefitscoverage":"http://www.cigna.com/2017/sbc/cigna-connect-6400-1-kc-mo",
        "sbchavingsimplefracturecoinsurance":"$0",
        "tehbdedcombinnoonfamilyperperson":"per person not applicable",
        "tehbdedoutofnetindividual":"Not Applicable",
        "sbchavingababylimit":"$30",
        "tehbinntier1individualmoop":"$7,150",
        "indianplanvariationestimatedadvancedpaymentamountperenrollee":"$0.00",
        "beginprimarycaredeductiblecoinsuranceafternumberofcopays":0,
        "planbrochure":"http://www.cigna.com/2017/sob/cigna-connect-6400-1-kc-mo",
        "ehbpercenttotalpremium":1,
        "sbchavingdiabeteslimit":"$280",
        "compositeratingoffered":"No",
        "issuerid":"74483",
        "tehbcombinnoonindividualmoop":"Not Applicable",
        "medicaldrugdeductiblesintegrated":"Yes",
        "sbchavingababycopayment":"$1,700",
        "beginprimarycarecostsharingafternumberofvisits":0,
        "outofserviceareacoverage":"Yes",
        "statecode":"MO",
        "uniqueplandesign":"Yes",
        "planexpirationdate":"2017-12-31",
        "childonlyoffering":"Allows Adult and Child-Only",
        "planeffictivedate":"2017-01-01",
        "isnoticerequiredforpregnancy":"No",
        "medicaldrugmaximumoutofpocketintegrated":"Yes",
        "formularyid":"MOF002",
        "inpatientcopaymentmaximumdays":0,
        "nationalnetwork":"No",
        "isreferralrequiredforspecialist":"No",
        "outofserviceareacoveragedescription":"Emergency Services Only",
        "multipleinnetworktiers":"No",
        "sourcename":"HIOS",
        "hpid":"7730182962",
        "isnewplan":"New",
        "planid":"74483MO0040012-03",
        "planvariantmarketingname":"Cigna Connect 6400-1",
        "tehbcombinnoonfamilyperpersonmoop":"per person not applicable",
        "tehbdedinntier1individual":"$6,400",
        "plantype":"EPO",
        "metallevel":"Bronze",
        "sbchavingsimplefracturecopayment":"$0",
        "formularyurl":"http://www.cigna.com/ifp-drug-list",
        "tehbdedinntier1coinsurance":"50.00%",
        "planmarketingname":"Cigna Connect 6400",
        "issueractuarialvalue":"60.08%",
        "tehbdedinntier1familyperperson":"$6400 per person",
        "sbchavingababydeductible":"$5,460" 
    }
]